### ISSUE TITLE
hsp2rgb conversion error

### ISSUE THREAD

**Issue by andrasbari** [reiniiriarios/chromaticity-color-utilities#3]
If I convert RGB color with rgb2hsp and convert back to RGB from the previously calculated HSP with hsp2rgb, the results are not the same. I made the test with no rounding. The rgb2hsp subrutine is good. The hsp2rgb have miscalculations.
for example:

RGB in: 
    "r": 66,
    "g": 114,
    "b": 242,

HSP out: 
    "h": 223.63636363636363,
    "s": 72.72727272727273,
    "p": 48.99197966515496,

convert HSP back to RGB:
    "r": 76,
    "g": 131,
    "b": 255,

It is not the same!

I have no more time to debug where can be the miscalculation. I found a 100% working algorithm in this project: https://github.com/colorjs/color-space/blob/master/hsp.js
It can be ported easily.

**Comment by reiniiriarios** [comment]
Thanks! Made some typos. 🙃 This should be fixed.
