### ISSUE TITLE
Color.from is not a function

### ISSUE THREAD

**Issue by jaarnio** [reiniiriarios/chromaticity-color-utilities#7]
I'm trying this out for first time, using the sample code and I'm getting this error that Color.from is not a function.

**Comment by reiniiriarios** [comment]
Hi @jaarnio! Oops. This is an ES5 issue, if I'm looking at the same issue. I'm not sure how it escaped me.

This is sending me down a rabbit hole trying to find an elegant solution, but for the time being you should be able to simply append `.default` to the end of the require statement, i.e.

```js
const Color = require('chromaticity-color-utilities').default
```

The next release will have a better solution.

**Comment by reiniiriarios** [comment]
@jaarnio If you update to the latest version, `0.14.0-alpha`, you can now use the following without error:
```js
const Color = require('chromaticity-color-utilities')
const color1 = Color.from('rgb', [50,100,150])
```

Typescript use has also been updated to nest types within `Color` rather than `{ colorTypes }`.
```ts
import Color from 'chromaticity-color-utilities'
const color1: Color.rgb = Color.from('rgb', [50,100,150])
```
